<a href="https://colab.research.google.com/github/georgevallejo/LG_Python_Projects/blob/main/Second_Assignment_car_stats_analysis_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Assigment:
# 1 understand the data first (head, describe, etc.)
# 2 clean the dataset by naming the missing column name
# 3 create a new dataframe that consists of a subset of the original
##  columns (only mpg, hp, wt, and cyl)
# 4 rename the above columns (cylinders = cyl)
# 5 summary statistics for those columns (average mpg)
# 6 filter your data and find summary statistics for only one type of vehicle
# data source:
# https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/refs/heads/master/mtcars.csv
# Executed Assigment CELLS from 0 to 13.
# Jorge Vallejo 8/31/2026

In [2]:
# Cell 0
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/mtcars.csv')

In [4]:
# Cell 1 Question1
# Shows the first 5 rows and numeric summary with nice Colab formatting.
# df.counts() and df.info() would show if there is missing values.
from IPython.display import display

sections = {
    "HEAD": df.head(),
    "SHAPE": df.shape,
    "DESCRIBE": df.describe(),
    "COUNT": df.count()
}

for title, content in sections.items():
    print(f"===== {title} =====")
    display(content)   # Pretty HTML table in Colab / this code is ignored in python scripts
    print("\n")

# # Head shows the first 5 rows
# Shape 32 rows and 12 columns
# describe statistics for numeric columns. 32 rows.  cyl: 6, 4, and 8. hp: b/w 93 to 173, geear 3-4, carb 1 to 4
# # # mpg = miles per gallon, cyl = engine cylinders, disp = engine displacement (cu in),
# # # hp = horsepower, drat = rear axle ratio, wt = weight (1000 lbs), qsec = quarter‑mile time (sec),
# # # vs = engine type (0 = V‑shaped, 1 = straight), am = transmission (0 = automatic, 1 = manual),
# # # gear = forward gears, carb = carburetors
# mean > median → right‑skewed mpg slightly. cyl, disp, hp
# mean < median → left‑skewed wt (keavier cars), qsec
# categories: vs, am, gear, carb
# based on  mean mediam and std-dev no outliers for mpg, draft and qsec.

===== HEAD =====

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

===== SHAPE =====

(32, 12)

===== DESCRIBE =====

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

===== COUNT =====

Unnamed: 0    32
mpg           32
cyl           32
disp          32
hp            32
drat          32
wt            32
qsec          32
vs            32
am            32
gear          32
carb          32
dtype: int64

In [5]:
# Cell 2  Question1

print("===== INFORMATION =====")
print('\nPrints the structure of the DataFrame: columns, dtypes, memory usage.\n')
df.info()
print('\n')
# first column 0 unnamed / string in the dataframe
# it came from spreadsheet  with the first column "":   "","mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"

print("===== SHAPE / ATTRIBUTE =====")    # Tuple, printed normally
print("Rows:", df.shape[0])
print("Columns:", df.shape[1], "\n")


# df.columns Displays all column names in the DataFrame.
# Helps understand the dataset structure.

print("\n===== COLUMNS / ATTRIBUTE =====")
print(df.columns)

===== INFORMATION =====

Prints the structure of the DataFrame: columns, dtypes, memory usage.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


===== SHAPE / ATTRIBUTE =====
Rows: 32
Columns: 12


===== COLUMNS / ATTRIBUTE =====
Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [6]:
# Cell 3  Question1
# Displays the number of missing values per column.  Check cell #2 for redundancy.
# Helps identify data cleaning needs.

df.isna().sum()

Unnamed: 0    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
dtype: int64

In [7]:
# Cell 4  Question1
# Shows how many unique values each column has.
# hels to understand category diversity.

df.nunique()

Unnamed: 0    32
mpg           25
cyl            3
disp          27
hp            22
drat          22
wt            29
qsec          30
vs             2
am             2
gear           3
carb           6
dtype: int64

In [8]:
# Cell 5 Question2 : How to clean the dataset by naming the missing column name
# df.info() shows the firts column as Unamed.
# renaming this column and updating the dataframe:
df.rename(columns={"Unnamed: 0": "vehicle"}, inplace=True)
df.head()

,vehicle,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
# Cell 6 Question3
# Create a dataframe with only the required columns.

# vehicle_stats_df = df[["mpg", "hp", "wt", "cyl"]]         # This is only a comment to check in future stats. panda

vehicle_stats_df = df[["mpg", "hp", "wt", "cyl"]].copy()  # independent dataframe multiple columns using a list ([[ ]]).

print(type(vehicle_stats_df),'\n' )
print("New subset: vehicle_stats_df\n")

display(vehicle_stats_df.head())         # used display otherwise it does not head() would not print anything to the terminal

print("\n===== SHAPE / ATTRIBUTE =====") # Tuple, printed normally
print("Rows:", vehicle_stats_df.shape[0])
print("Columns:", vehicle_stats_df.shape[1], "\n")

<class 'pandas.core.frame.DataFrame'>

New subset: vehicle_stats_df

    mpg   hp     wt  cyl
0  21.0  110  2.620    6
1  21.0  110  2.875    6
2  22.8   93  2.320    4
3  21.4  110  3.215    6
4  18.7  175  3.440    8

===== SHAPE / ATTRIBUTE =====
Rows: 32
Columns: 4

In [10]:
# Cell 7 Question4 rename the columns with full names
vehicle_stats_df.rename(
    columns={
        "mpg": "Mileage",
        "hp": "Horsepower",
        "wt": "Weight",
        "cyl": "Cylinders"
    },
    inplace=True
)

vehicle_stats_df.head()

   Mileage  Horsepower  Weight  Cylinders
0     21.0         110   2.620          6
1     21.0         110   2.875          6
2     22.8          93   2.320          4
3     21.4         110   3.215          6
4     18.7         175   3.440          8

In [11]:
# cell 8 gave me the following warning:
# /tmp/ipykernel_1119/1322232968.py:2: SettingWithCopyWarning:
# A value is trying to be set on a copy of a slice from a DataFrame
#
# See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
#  vehicle_stats_df.rename(

# Therefore; I added .copy() to the end of the expression in cell # 3 otherwise pandas was thinking is only a view.


# The warning occurred because vehicle_stats_df was created as a
# subset of the original dataframe. Pandas could not determine
# whether changes should affect only the subset or the original
# dataframe. Using .copy() when creating vehicle_stats_df creates
# an independent dataframe and removes the warning.

In [12]:
# Cell 9 Question5
# Summary statistics for the selected columns.

vehicle_stats_df.describe()

         Mileage  Horsepower     Weight  Cylinders
count  32.000000   32.000000  32.000000  32.000000
mean   20.090625  146.687500   3.217250   6.187500
std     6.026948   68.562868   0.978457   1.785922
min    10.400000   52.000000   1.513000   4.000000
25%    15.425000   96.500000   2.581250   4.000000
50%    19.200000  123.000000   3.325000   6.000000
75%    22.800000  180.000000   3.610000   8.000000
max    33.900000  335.000000   5.424000   8.000000

In [13]:
# Cell 10 Question5
# Calculate the average fuel efficiency.

average_Mileage = vehicle_stats_df["Mileage"].mean()

print(f"Average MPG: {average_Mileage:.2f}")

Average MPG: 20.09

In [14]:
# Cell 10.1 Using df.loc
# Calculate the average fuel efficiency using loc
average_mpg_4cyl = vehicle_stats_df.loc[
    vehicle_stats_df["Cylinders"] == 4,
    "Mileage"
].mean()
print(f"Average mpg_4cyl:  {average_mpg_4cyl:.2f}")

Average mpg_4cyl:  26.66

In [15]:
# Cell 11 Question 6 Filter for all vehicles using 4 cylinders
# Filter only 4-cylinder vehicles using loc.

four_cylinder_df = vehicle_stats_df.loc[
    vehicle_stats_df["Cylinders"] == 4
]

display(four_cylinder_df.head())

    Mileage  Horsepower  Weight  Cylinders
2      22.8          93   2.320          4
7      24.4          62   3.190          4
8      22.8          95   3.150          4
17     32.4          66   2.200          4
18     30.4          52   1.615          4

In [16]:
# Cell 11.1
# Create a dataframe containing only 4-cylinder vehicles.

four_cylinder_df = vehicle_stats_df[
    vehicle_stats_df["Cylinders"] == 4
]
print(four_cylinder_df.head())
# display(four_cylinder_df.head())  # keeping this line only as a reference to collab and juniper lab
print('\n')
print("\n===== DATAFRAME INFO =====\n")
four_cylinder_df.info()

    Mileage  Horsepower  Weight  Cylinders
2      22.8          93   2.320          4
7      24.4          62   3.190          4
8      22.8          95   3.150          4
17     32.4          66   2.200          4
18     30.4          52   1.615          4



===== DATAFRAME INFO =====

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 2 to 31
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Mileage     11 non-null     float64
 1   Horsepower  11 non-null     int64
 2   Weight      11 non-null     float64
 3   Cylinders   11 non-null     int64
dtypes: float64(2), int64(2)
memory usage: 440.0 bytes

In [17]:
# Cell 11.2  filter using iloc[0] using the new four_cylinder_df dataframe
# Example: display the first 4-cylinder vehicle using iloc

four_cylinder_df.iloc[0]

Mileage       22.80
Horsepower    93.00
Weight         2.32
Cylinders      4.00
Name: 2, dtype: float64

In [18]:
# Cell 12
# Compare fuel efficiency of 4-cylinder vehicles.

average_mpg_4cyl = four_cylinder_df["Mileage"].mean()

print(f"Average MPG for 4-cylinder vehicles: {average_mpg_4cyl:.2f}")
print()
print(type(four_cylinder_df))

Average MPG for 4-cylinder vehicles: 26.66

<class 'pandas.core.frame.DataFrame'>

In [19]:
# ============================================================
# CELL 13 CONCLUSION
#
# The dataset contains 32 vehicles and 12 columns.
# No missing values were found in any column.
# The unnamed vehicle column was renamed to "vehicle"
#
# A subset dataframe named vehicle_stats_df was created
# containing fuel efficiency (mpg), horsepower (hp),
# weight (wt), and number of cylinders (cyl).
#
# The overall average fuel efficiency is 20.09 mpg
#
# After filtering for 4-cylinder vehicles, the average
# mpg is 26.66 MPG, fewer cylinders = more efficiency

# ============================================================

In [20]:
# ============================================================
# ASSIGNMENT REQUIREMENTS (Lecture 3 - Vehicle Gas Mileage Data)
#
# 1. Understand the dataset
#    - Display the first few rows using head()
#    - Review dataset dimensions using shape
#    - Review summary statistics using describe()
#    - Check for missing values using count(), info(), or isna().sum()
#
# 2. Clean the dataset
#    - Identify the unnamed column
#    - Rename "Unnamed: 0" to "vehicle"
#
# 3. Create a subset dataframe
#    - Create a new dataframe containing only:
#         mpg
#         hp
#         wt
#         cyl
#
# 4. Rename columns
#    - Rename cyl to Cylinders
#    - Optionally rename other columns to improve readability
#
# 5. Generate summary statistics
#    - Use describe() on the subset dataframe
#    - Calculate the average MPG (Mileage)
#
# 6. Filter the dataset
#    - Filter for one vehicle category
#    - vehicles with 4 cylinders
#
# 7. Generate summary statistics for the filtered data
#    - Display descriptive statistics for 4-cylinder vehicles
#    - Calculate the average MPG for 4-cylinder vehicles
#

In [21]:
# 8. Additional DataFrame Operations
#    - Create a new calculated column:
#         efficiency_weight_ratio = mpg / wt
#    - Display and analyze the new column
#    - Remove the temporary column using drop()
#
# 9. Row Manipulation
#    - Add a temporary vehicle named "Test Car"
#    - Verify the dataframe size increases
#    - Remove the temporary vehicle
#    - Verify the dataframe returns to its original size
#
# ============================================================

In [22]:
# Cell Opitonal
# Add a new test vehicle row to the original dataframe.

new_vehicle = {
    "vehicle": "Test Car",
    "mpg": 35.0,
    "cyl": 4,
    "disp": 120.0,
    "hp": 95,
    "drat": 3.90,
    "wt": 2.10,
    "qsec": 19.0,
    "vs": 1,
    "am": 1,
    "gear": 5,
    "carb": 2
}

# Add the new row at the bottom of the dataframe.
df.loc[len(df)] = new_vehicle

print("New vehicle added.\n")
display(df.tail())

New vehicle added.

,vehicle,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.17,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.77,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.57,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.78,18.6,1,1,4,2
32,Test Car,35.0,4,120.0,95,3.90,2.10,19.0,1,1,5,2

In [23]:
# Cell Optional
# Verify that the dataframe now contains one additional row.

print("Updated Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Updated Shape:
Rows: 33
Columns: 12

In [24]:
# Cell Optional
# Remove the temporary test vehicle using its unique vehicle name.

df = df[df["vehicle"] != "Test Car"]

print("Test Car removed.\n")
display(df.tail())

Test Car removed.

,vehicle,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [25]:
# Cell Optional
# Create a new column that measures fuel efficiency relative
# to vehicle weight. Larger values indicate better fuel
# efficiency for the vehicle's weight.

df["efficiency_weight_ratio"] = df["mpg"] / df["wt"]

print(
    df[["vehicle", "mpg", "wt", "efficiency_weight_ratio"]]
    .head()
)

             vehicle   mpg     wt  efficiency_weight_ratio
0          Mazda RX4  21.0  2.620                 8.015267
1      Mazda RX4 Wag  21.0  2.875                 7.304348
2         Datsun 710  22.8  2.320                 9.827586
3     Hornet 4 Drive  21.4  3.215                 6.656299
4  Hornet Sportabout  18.7  3.440                 5.436047

In [26]:
# Cell Optional
# Display summary statistics for the newly created
# efficiency_weight_ratio column.

print(df["efficiency_weight_ratio"].describe())

count    32.000000
mean      7.494852
std       4.882538
min       1.917404
25%       4.352977
50%       5.508721
75%       8.191978
max      20.092531
Name: efficiency_weight_ratio, dtype: float64

In [27]:
# Cell Optional
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   vehicle                  32 non-null     object
 1   mpg                      32 non-null     float64
 2   cyl                      32 non-null     int64
 3   disp                     32 non-null     float64
 4   hp                       32 non-null     int64
 5   drat                     32 non-null     float64
 6   wt                       32 non-null     float64
 7   qsec                     32 non-null     float64
 8   vs                       32 non-null     int64
 9   am                       32 non-null     int64
 10  gear                     32 non-null     int64
 11  carb                     32 non-null     int64
 12  efficiency_weight_ratio  32 non-null     float64
dtypes: float64(6), int64(6), object(1)
memory usage: 3.5+ KB

In [28]:
# Cell Optional
# Remove the temporary efficiency_weight_ratio column.

df.drop("efficiency_weight_ratio", axis=1, inplace=True)

print("efficiency_weight_ratio column removed.\n")
print(df.columns)

efficiency_weight_ratio column removed.

Index(['vehicle', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [29]:
# @title cell#1 backup code  / do not execute
# Cell X — Full EDA Summary

# print("===== HEAD =====")
# print(df.head(), "\n")   # First 5 rows of the dataset

# print("===== SHAPE =====")
# print(df.shape, "\n")    # Number of rows and columns

# print("===== DESCRIBE =====")
# print(df.describe(), "\n")   # Numeric summary statistics

# print("===== CATEGORICAL SUMMARY =====")
# print(df.describe(include='object'), "\n")   # Summary for string columns

# print("===== UNIQUE COUNTS =====")
# print(df.nunique(), "\n")   # Unique values per column

# print("===== MISSING VALUES =====")
# print(df.isna().sum(), "\n")   # Missing values per column

# print("===== CORRELATION MATRIX =====")
# print(df.corr(numeric_only=True), "\n")   # Correlation between numeric columns

# print("===== INFO =====")
# df.info()   # Prints DataFrame structure

In [30]:
# Cell Optional
# Computes correlations between numeric columns.
# Helps identify relationships between variables.

# df.corr(numeric_only=True)
# request the Professor to explain.

In [31]:
# The correlation matrix shows that vehicle weight (-0.868)
# and number of cylinders (-0.852) have the strongest negative
# relationships with fuel economy (mpg), indicating that heavier
# vehicles and those with more cylinders tend to be less fuel efficient.